import { AnimatedGroup } from '@/components/animated-group';
import { ArrowUpRight, ArrowDown, Sparkles, Layers, MoveUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AmbientSound } from '@/components/ambient-sound';
const notion = '/work/';
const projects = [
{ name:'MyYogaTeacher',title:'Making the next session a natural choice.',text:'A retention experience built around visible progress, personalised recommendations, and continuity with teachers.',tags:'Retention / Personalisation',href:'https://spec-to-spark-62.lovable.app',color:'mint',word:'Keep\nshowing up.',label:'CONSUMER HEALTH'},
{ name:'Playo',title:'From finding a game to finding your people.',text:'Connecting discovery, participation, community, venue supply, and rewards into a sustainable growth loop.',tags:'Growth loops / Marketplace',href:'https://hire-me-demo.lovable.app',color:'orange',word:'Find. Play.\nRepeat.',label:'COMMUNITY & SPORT'},
{ name:'Cult',title:'One clear picture of a complex business.',text:'An operations intelligence layer for founders, finance, marketing, coaches, and trainers to make better decisions.',tags:'Operations / B2B platforms',href:'https://cult-case-path.lovable.app/case-study.html',prototype:'https://cult-case-path.lovable.app/prototype.html',color:'purple',word:'Clarity\nat every level.',label:'OPERATIONS INTELLIGENCE'},
{ name:'Autonomous SEO Operator',title:'A growth system that learns as it works.',text:'An agentic system to research opportunities, plan content, execute workflows, and improve through feedback.',tags:'Agentic AI / Growth automation',href:'/work/autonomous-seo-operator',color:'blue',word:'Research.\nAct. Learn.',label:'AI-NATIVE WORKFLOWS'},
{ name:'Gridfall 2035',title:'Every decision changes the city.',text:'A browser strategy game set in a collapsing futuristic Bangalore. Balance essential resources, public trust, and competing factions.',tags:'Systems thinking / Civic technology',href:'https://build-a-browser-based-emergent-civi.vercel.app/',color:'yellow',word:'A city on\nthe edge.',label:'EMERGENT SIMULATION'},
{ name:'Voiceera GTM Radar',title:'Hear the market before it moves.',text:'A GTM intelligence prototype that turns customer and market signals into clear decisions for growth teams.',tags:'GTM intelligence / Voice AI',href:'https://voiceera-gtm-radar.streamlit.app/',color:'violet',word:'Listen.\nLearn. Act.',label:'GTM INTELLIGENCE'},
{ name:'Buildathon',title:'An idea is only the starting point.',text:'Taking a concept to a working web experience in a time-bound buildathon, using AI-assisted building and rapid iteration.',tags:'Prototyping / Product execution',href:'https://buildathon-5q8q46qva-premsameers-projects.vercel.app/',color:'pink',word:'Think it.\nShip it.',label:'RAPID PRODUCT BUILDING'}];
const work = [
['Smart Course Recommender','AI product','Shortlisting: ~25 min → ~7 min','34b0733b4c2481e685d1d31567b9eb2a'],
['AI Document Intelligence','AI agents','~65% less manual review time; adoption remains a challenge','34b0733b4c2481878d5fc59d52a744ce'],
['AI Meeting Insights Generator','AI workflows','From conversations to actionable insights','34b0733b4c24812f805ed690b270b7cb'],
['Sekel Tech Platform','B2B2C SaaS','MarTech platform','34b0733b4c2481a2922cdbc262c19ca6'],
['Conversion Funnel Optimisation','Growth','Meeting-to-applicant conversion: 15% → 18% YoY','34b0733b4c2481e3b348d0d02ac07074'],
['Counsellor Tool Adoption','GTM & change','Adoption as a product problem','34b0733b4c248108b6bde7e1d031b3b8'],
['B2B Agency Portal Revamp','UX & growth','Improving the agency experience','34b0733b4c248194a324d77293dd1bae'],
['How I Think & Work','PM approach','The thinking behind the decisions','34b0733b4c24818b977af32dc142265c']];
export default function Home(){return <main id="top">
<a className="skip" href="#work">Skip to work</a>
<header className="nav wrap"><a className="brand" href="#top" aria-label="Prem Sameer home">Prem Sameer</a><nav aria-label="Main navigation"><a href="#work">Selected work</a><a href="#about">About</a><a href="#contact">Let’s talk <ArrowUpRight size={16}/></a></nav><AmbientSound /></header>
<section className="hero wrap"><div className="eyebrow">PREM SAMEER <span>PRODUCT MANAGER · BANGALORE</span></div><h1><span className="hero-title-main">Wicked problems</span>{" "}<span className="serif">and creativity.</span></h1><div className="hero-bottom"><p>I build AI-powered products and growth systems that move the needle for users.<br/><span>10+ years across B2B SaaS, EdTech, MarTech, FinTech, and SalesTech.</span></p><Button asChild className="cta"><a href="#work">Read the field notes <ArrowDown/></a></Button></div><div className="hero-foot"><span>Currently building AI & Growth at <strong>AECC Global</strong></span><span>Open to Senior / Lead PM roles</span></div></section>
<section id="work" className="work wrap"><div className="section-top"><div><span className="eyebrow">01 / SELECTED EXPLORATIONS</span><h2>Thinking made tangible.</h2></div><p>Product problems, considered deeply.<br/>Ideas, taken all the way to an experience.</p></div><AnimatedGroup className="project-grid">{projects.map((p,i)=><article className="project" key={p.name}><a href={p.href} target={p.href.startsWith("/") ? undefined : "_blank"} rel="noreferrer" className={`project-art ${p.color}`} aria-label={`Explore ${p.name}`}><div className="art-meta"><span>{p.label}</span><span>{String(i+1).padStart(2,"0")} / 07</span></div><div className="art-word">{p.word}</div><div className="art-bottom"><span>{p.name}</span><span className="round-arrow"><ArrowUpRight/></span></div></a><div className="project-copy"><span className="eyebrow">{p.tags}</span><h3><a href={p.href} target={p.href.startsWith("/") ? undefined : "_blank"} rel="noreferrer">{p.title}</a></h3><p>{p.text}</p>{p.prototype&&<a className="text-link" href={p.prototype} target="_blank" rel="noreferrer">Open prototype <ArrowUpRight size={16}/></a>}</div></article>)}</AnimatedGroup></section>
<section className="experience wrap" id="experience"><div className="section-top"><div><span className="eyebrow">02 / WORK IN PRACTICE</span><h2>Inside the work.</h2></div><p>Discovery, trade-offs, delivery, and lessons.<br/>The full stories behind real initiatives.</p></div><div className="work-list">{work.map(([name,tag,result,id],i)=><a key={id} href={notion+id} className="work-row"><span className="index">0{i+1}</span><div><h3>{name}</h3><p>{result}</p></div><span className="pill">{tag}</span><ArrowUpRight className="row-arrow"/></a>)}</div></section>
<section id="about" className="about"><div className="wrap about-grid"><div><span className="eyebrow">03 / THE PERSON BEHIND THE PRODUCT</span><h2>Curious by nature.<br/><span className="serif">Intentional</span> by practice.</h2><div className="about-sign">Prem Sameer <MoveUpRight size={38}/></div></div><div><p className="about-lead">I sit at the intersection of AI product development, growth systems, and user-centric design.</p><p>I care deeply about the why behind decisions. My north star is to ship things that measurably move the needle for users and the business, in that order.</p><div className="principle"><Sparkles/><div><h3>Discover ruthlessly.</h3><p>Start with interviews, surveys, and co-design. Understand the problem before writing the spec.</p></div></div><div className="principle"><Layers/><div><h3>Build carefully.</h3><p>Answer why now, why this, and why this shape. Make small bets, learn fast, and keep iterating.</p></div></div><div className="principle"><MoveUpRight/><div><h3>Measure honestly.</h3><p>Treat adoption as a product problem. Be as clear about what didn’t work as what did.</p></div></div></div></div></section>
<footer id="contact" className="wrap"><span className="eyebrow">HAVE A PRODUCT PROBLEM WORTH SOLVING?</span><a className="contact-title" href="mailto:sameerprem1405@gmail.com">Let’s build<br/><span className="serif">what’s next.</span><ArrowUpRight/></a><div className="contact-details"><a href="mailto:sameerprem1405@gmail.com">sameerprem1405@gmail.com</a><a href="tel:+918970870925">+91 8970870925</a><span>Bangalore, India</span></div><div className="footer-bottom"><span>© 2026 Prem Sameer</span><div>{[['LinkedIn','https://www.linkedin.com/in/prem-sameer-95971751/'],['GitHub','https://github.com/premsameer'],['Medium','https://medium.com/@premsameer14'],['Behance','https://www.behance.net/prems'],['Instagram','https://www.instagram.com/premsameer/']].map(([n,h])=><a key={n} href={h} target="_blank" rel="noreferrer">{n}<ArrowUpRight size={14}/></a>)}</div><a href="#top">Back to top ↑</a></div></footer></main>}


